### PR TITLE
Fix switching from custom view to custom view

### PR DESCRIPTION
**Pull request by Matthbo**

### CODE REVIEW

**Review by nielsm5 — APPROVED** [review]

**Review by philipsens — COMMENTED** [review]
I still have the bug, when I test this locally.

Could you try using these environment variables: 
```
customViews.google.name=Google;customViews.google.url=https://google.com/;customViews.ladybug.name=Ladybug;customViews.ladybug.url=iaf/ladybug;customViews.names=ladybug,google
```
(These can be pasted intro the IntelliJ run configuration)

**Comment by Matthbo** [comment]
```-DcustomViews.google.name=Google;customViews.google.url=https://google.com/;customViews.ladybug.name=Ladybug;customViews.ladybug.url=iaf/ladybug;customViews.names=ladybug,google
```
doesnt seem to actually work, it even breaks tomcat if I remove `-D`

**Comment by Matthbo** [comment]
And it seems to work as expected for me

**Review by nielsm5 — CHANGES_REQUESTED** [review]
Bij mij werkt het ook niet 😢

**Review by nielsm5 — APPROVED** [review]

**Pull request merged**
